# Generated by Django 4.2.13 on 2026-08-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_moodentry_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='tag',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='energy_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
