# Generated by Django 4.2.13 on 2026-08-21 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_remove_moodentry_created_at_remove_moodentry_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
